spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rhythmix
    username: postgres
    password: nNf4rfrk
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: rhythmix.official.webapp@gmail.com
    password: ujer fkgv kfmj cwxq
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

security:
  jwt:
    secret-key: qwforwpepipwqewkufcowgilcfliwnrfiugio149y9432y7kibcfi
    expiration-time: 3600000

spring.config.import: optional:file:.env[.properties]
